# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: AC - Sync Strings

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  main:
    name: Sync strings
    runs-on: ubuntu-latest
    steps:
      - name: Discover A-C version
        id: discover-version
        uses: mozilla-mobile/ac-version-for-fenix-beta@1.3.0
      - name: Store ENV variables
        id: env-variables
        run: |
          echo "project_name=AC Strings" >> $GITHUB_OUTPUT
          echo "beta_branch=releases_v${{ steps.discover-version.outputs.major-ac-version }}" >> $GITHUB_OUTPUT
          echo "branch_name=automation/sync-ac-strings-${{ steps.discover-version.outputs.major-ac-version }}" >> $GITHUB_OUTPUT
      - name: Checkout Default Branch
        uses: actions/checkout@v3
        with:
          path: default
      - name: Checkout beta branch
        uses: actions/checkout@v3
        with:
          path: beta
          ref: ${{ steps.env-variables.outputs.beta_branch }}
      - name: Sync strings
        uses: flodolo/sync-strings-action@main
        with:
          toml_path: android-components/l10n.toml
          src: default
          dest: beta
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: beta
          branch: ${{ steps.env-variables.outputs.branch_name }}
          title: "Uplift ${{ steps.env-variables.outputs.project_name }} from ${{ github.ref_name }} to ${{ steps.env-variables.outputs.beta_branch }}"
          body: "This (automated) PR syncs strings from `${{ github.ref_name }}` to `${{ steps.env-variables.outputs.beta_branch }}`"
